# Generated by Django 5.2.3 on 2025-06-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Upload network topology image', upload_to='uploads/')),
                ('task', models.TextField(help_text='Enter the task description')),
                ('questions', models.TextField(help_text='Enter the questions (one per line or paragraph)')),
                ('lab_answers', models.TextField(help_text='Enter the correct lab answers')),
                ('user_answers', models.TextField(blank=True, help_text="User's submitted answers")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
