# Generated by Django 4.2.7 on 2025-07-11 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab_simulations', '0002_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labsimulation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lab Simulation', 'verbose_name_plural': 'Lab Simulations'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='attempted_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='labsimulation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='image',
            field=models.ImageField(blank=True, help_text='Network topology image', null=True, upload_to='lab_images/'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='lab_answers',
            field=models.TextField(help_text='Correct answers for the lab questions'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='questions',
            field=models.TextField(help_text='Questions for students to answer'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='task',
            field=models.TextField(help_text='Description of the task students need to complete'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='title',
            field=models.CharField(help_text='Title of the lab simulation', max_length=200),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='user_answers',
            field=models.TextField(blank=True, help_text="User's submitted answers", null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(blank=True, help_text='Score percentage', null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user_answers',
            field=models.TextField(help_text="User's submitted answers"),
        ),
    ]
