# Generated by Django 4.2.7 on 2025-07-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_simulations', '0003_alter_labsimulation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labsimulation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='labsimulation',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='image',
            field=models.ImageField(help_text='Upload network topology image', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='lab_answers',
            field=models.TextField(help_text='Enter the correct lab answers'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='questions',
            field=models.TextField(help_text='Enter the questions (one per line or paragraph)'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='task',
            field=models.TextField(help_text='Enter the task description'),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labsimulation',
            name='user_answers',
            field=models.TextField(blank=True, help_text="User's submitted answers"),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
