# Generated by Django 4.2.7 on 2025-07-11 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_simulations', '0004_alter_labsimulation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lab_simulations.labsimulation')),
            ],
            options={
                'ordering': ['-attempt_date'],
            },
        ),
    ]
